# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gbfs_now
                                 A QGIS plugin
 view gbfs-data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-21
        copyright            : (C) 2022 by Kohta Hisadomi
        email                : his.koh3.biz@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load gbfs_now class from file gbfs_now.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gbfs_now import gbfs_now
    return gbfs_now(iface)
